# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mathworks/scenario/common/coordinate_system.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mathworks.scenario.common import geometry_pb2 as mathworks_dot_scenario_dot_common_dot_geometry__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1mathworks/scenario/common/coordinate_system.proto\x12\x19mathworks.scenario.common\x1a(mathworks/scenario/common/geometry.proto\"\x90\x03\n\x19\x43oordinateReferenceSystem\x12L\n\x1bprojected_coordinate_system\x18\x0b \x01(\x0b\x32%.mathworks.scenario.common.ProjectionH\x00\x12]\n\x1cgeographic_coordinate_system\x18\x0c \x01(\x0b\x32\x35.mathworks.scenario.common.GeographicCoordinateSystemH\x00\x12]\n\x1cgeocentric_coordinate_system\x18\r \x01(\x0b\x32\x35.mathworks.scenario.common.GeocentricCoordinateSystemH\x00\x12_\n\x1d\x65ngineering_coordinate_system\x18\x0e \x01(\x0b\x32\x36.mathworks.scenario.common.EngineeringCoordinateSystemH\x00\x42\x06\n\x04type\"\x1c\n\x1aGeographicCoordinateSystem\"\x1c\n\x1aGeocentricCoordinateSystem\"f\n\x1b\x45ngineeringCoordinateSystem\x12G\n\x0fgeodetic_origin\x18\x01 \x01(\x0b\x32..mathworks.scenario.common.GeodeticCoordinates\"L\n\x13GeodeticCoordinates\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\x12\x10\n\x08\x61ltitude\x18\x03 \x01(\x01\"p\n\x13\x43oordinateSystemRef\x12Q\n\x11\x63oordinate_system\x18\x0b \x01(\x0b\x32\x34.mathworks.scenario.common.CoordinateReferenceSystemH\x00\x42\x06\n\x04typeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mathworks.scenario.common.coordinate_system_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_COORDINATEREFERENCESYSTEM']._serialized_start=123
  _globals['_COORDINATEREFERENCESYSTEM']._serialized_end=523
  _globals['_GEOGRAPHICCOORDINATESYSTEM']._serialized_start=525
  _globals['_GEOGRAPHICCOORDINATESYSTEM']._serialized_end=553
  _globals['_GEOCENTRICCOORDINATESYSTEM']._serialized_start=555
  _globals['_GEOCENTRICCOORDINATESYSTEM']._serialized_end=583
  _globals['_ENGINEERINGCOORDINATESYSTEM']._serialized_start=585
  _globals['_ENGINEERINGCOORDINATESYSTEM']._serialized_end=687
  _globals['_GEODETICCOORDINATES']._serialized_start=689
  _globals['_GEODETICCOORDINATES']._serialized_end=765
  _globals['_COORDINATESYSTEMREF']._serialized_start=767
  _globals['_COORDINATESYSTEMREF']._serialized_end=879
# @@protoc_insertion_point(module_scope)
