# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mathworks/scenario/common/core.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$mathworks/scenario/common/core.proto\x12\x19mathworks.scenario.common\"7\n\tColorRGBA\x12\t\n\x01r\x18\x01 \x01(\r\x12\t\n\x01g\x18\x02 \x01(\r\x12\t\n\x01\x62\x18\x03 \x01(\r\x12\t\n\x01\x61\x18\x04 \x01(\r\"F\n\x0e\x43olorRGBAArray\x12\x34\n\x06values\x18\x01 \x03(\x0b\x32$.mathworks.scenario.common.ColorRGBA\"\x1d\n\x0bStringArray\x12\x0e\n\x06values\x18\x01 \x03(\t\"\x1c\n\nFloatArray\x12\x0e\n\x06values\x18\x01 \x03(\x02\"\x1d\n\x0b\x44oubleArray\x12\x0e\n\x06values\x18\x01 \x03(\x01\"\x1b\n\tBoolArray\x12\x0e\n\x06values\x18\x01 \x03(\x08\"\x1c\n\nInt32Array\x12\x0e\n\x06values\x18\x01 \x03(\x05\"\x1d\n\x0bUInt32Array\x12\x0e\n\x06values\x18\x01 \x03(\r\"\x1c\n\nInt64Array\x12\x0e\n\x06values\x18\x01 \x03(\x03\"\x1d\n\x0bUInt64Array\x12\x0e\n\x06values\x18\x01 \x03(\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mathworks.scenario.common.core_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_COLORRGBA']._serialized_start=67
  _globals['_COLORRGBA']._serialized_end=122
  _globals['_COLORRGBAARRAY']._serialized_start=124
  _globals['_COLORRGBAARRAY']._serialized_end=194
  _globals['_STRINGARRAY']._serialized_start=196
  _globals['_STRINGARRAY']._serialized_end=225
  _globals['_FLOATARRAY']._serialized_start=227
  _globals['_FLOATARRAY']._serialized_end=255
  _globals['_DOUBLEARRAY']._serialized_start=257
  _globals['_DOUBLEARRAY']._serialized_end=286
  _globals['_BOOLARRAY']._serialized_start=288
  _globals['_BOOLARRAY']._serialized_end=315
  _globals['_INT32ARRAY']._serialized_start=317
  _globals['_INT32ARRAY']._serialized_end=345
  _globals['_UINT32ARRAY']._serialized_start=347
  _globals['_UINT32ARRAY']._serialized_end=376
  _globals['_INT64ARRAY']._serialized_start=378
  _globals['_INT64ARRAY']._serialized_end=406
  _globals['_UINT64ARRAY']._serialized_start=408
  _globals['_UINT64ARRAY']._serialized_end=437
# @@protoc_insertion_point(module_scope)
