# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mathworks/scenario/scene/hd/common_attributes.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3mathworks/scenario/scene/hd/common_attributes.proto\x12\x1emathworks.scenario.scene.hdmap\"7\n\x0fParametricRange\x12\x12\n\nspan_start\x18\x01 \x01(\x01\x12\x10\n\x08span_end\x18\x02 \x01(\x01\"\x8e\x01\n\x10\x41lignedReference\x12<\n\treference\x18\x01 \x01(\x0b\x32).mathworks.scenario.scene.hdmap.Reference\x12<\n\talignment\x18\x02 \x01(\x0e\x32).mathworks.scenario.scene.hdmap.Alignment\"\x17\n\tReference\x12\n\n\x02id\x18\x01 \x01(\t\"\'\n\x11RelativeAssetPath\x12\x12\n\nasset_path\x18\x01 \x01(\t\"\'\n\x08Metadata\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t*U\n\tAlignment\x12\x19\n\x15\x41LIGNMENT_UNSPECIFIED\x10\x00\x12\x15\n\x11\x41LIGNMENT_FORWARD\x10\x01\x12\x16\n\x12\x41LIGNMENT_BACKWARD\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mathworks.scenario.scene.hd.common_attributes_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_ALIGNMENT']._serialized_start=396
  _globals['_ALIGNMENT']._serialized_end=481
  _globals['_PARAMETRICRANGE']._serialized_start=87
  _globals['_PARAMETRICRANGE']._serialized_end=142
  _globals['_ALIGNEDREFERENCE']._serialized_start=145
  _globals['_ALIGNEDREFERENCE']._serialized_end=287
  _globals['_REFERENCE']._serialized_start=289
  _globals['_REFERENCE']._serialized_end=312
  _globals['_RELATIVEASSETPATH']._serialized_start=314
  _globals['_RELATIVEASSETPATH']._serialized_end=353
  _globals['_METADATA']._serialized_start=355
  _globals['_METADATA']._serialized_end=394
# @@protoc_insertion_point(module_scope)
