# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mathworks/scenario/scene/hd/hd_barriers.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mathworks.scenario.common import geometry_pb2 as mathworks_dot_scenario_dot_common_dot_geometry__pb2
from mathworks.scenario.scene.hd import common_attributes_pb2 as mathworks_dot_scenario_dot_scene_dot_hd_dot_common__attributes__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-mathworks/scenario/scene/hd/hd_barriers.proto\x12\x1emathworks.scenario.scene.hdmap\x1a(mathworks/scenario/common/geometry.proto\x1a\x33mathworks/scenario/scene/hd/common_attributes.proto\"n\n\x15\x42\x61rrierTypeDefinition\x12\n\n\x02id\x18\x01 \x01(\t\x12I\n\x0e\x65xtrusion_path\x18\x02 \x01(\x0b\x32\x31.mathworks.scenario.scene.hdmap.RelativeAssetPath\"\xac\x01\n\x07\x42\x61rrier\x12\n\n\x02id\x18\x01 \x01(\t\x12\x38\n\x08geometry\x18\x02 \x01(\x0b\x32&.mathworks.scenario.common.Vector3List\x12\x43\n\x10\x62\x61rrier_type_ref\x18\x03 \x01(\x0b\x32).mathworks.scenario.scene.hdmap.Reference\x12\x16\n\x0e\x66lip_laterally\x18\x04 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mathworks.scenario.scene.hd.hd_barriers_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_BARRIERTYPEDEFINITION']._serialized_start=176
  _globals['_BARRIERTYPEDEFINITION']._serialized_end=286
  _globals['_BARRIER']._serialized_start=289
  _globals['_BARRIER']._serialized_end=461
# @@protoc_insertion_point(module_scope)
