# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mathworks/scenario/scene/hd/hd_junctions.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mathworks.scenario.common import geometry_pb2 as mathworks_dot_scenario_dot_common_dot_geometry__pb2
from mathworks.scenario.scene.hd import common_attributes_pb2 as mathworks_dot_scenario_dot_scene_dot_hd_dot_common__attributes__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.mathworks/scenario/scene/hd/hd_junctions.proto\x12\x1emathworks.scenario.scene.hdmap\x1a(mathworks/scenario/common/geometry.proto\x1a\x33mathworks/scenario/scene/hd/common_attributes.proto\"\x8b\x01\n\x08Junction\x12\n\n\x02id\x18\x01 \x01(\t\x12\x39\n\x08geometry\x18\x02 \x01(\x0b\x32\'.mathworks.scenario.common.MultiPolygon\x12\x38\n\x05lanes\x18\x03 \x03(\x0b\x32).mathworks.scenario.scene.hdmap.Referenceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mathworks.scenario.scene.hd.hd_junctions_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_JUNCTION']._serialized_start=178
  _globals['_JUNCTION']._serialized_end=317
# @@protoc_insertion_point(module_scope)
