# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mathworks/scenario/scene/hd/hd_lane_markings.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mathworks.scenario.scene.hd import common_attributes_pb2 as mathworks_dot_scenario_dot_scene_dot_hd_dot_common__attributes__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2mathworks/scenario/scene/hd/hd_lane_markings.proto\x12\x1emathworks.scenario.scene.hdmap\x1a\x33mathworks/scenario/scene/hd/common_attributes.proto\"`\n\x0bLaneMarking\x12\n\n\x02id\x18\x01 \x01(\t\x12\x45\n\nasset_path\x18\x02 \x01(\x0b\x32\x31.mathworks.scenario.scene.hdmap.RelativeAssetPath\"i\n\x10MarkingReference\x12=\n\nmarking_id\x18\x01 \x01(\x0b\x32).mathworks.scenario.scene.hdmap.Reference\x12\x16\n\x0e\x66lip_laterally\x18\x02 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mathworks.scenario.scene.hd.hd_lane_markings_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_LANEMARKING']._serialized_start=139
  _globals['_LANEMARKING']._serialized_end=235
  _globals['_MARKINGREFERENCE']._serialized_start=237
  _globals['_MARKINGREFERENCE']._serialized_end=342
# @@protoc_insertion_point(module_scope)
