# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mathworks/roadrunner/core.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fmathworks/roadrunner/core.proto\x12\x14mathworks.roadrunner*Z\n\x0b\x44rivingSide\x12\x1c\n\x18\x44RIVING_SIDE_UNSPECIFIED\x10\x00\x12\x15\n\x11\x44RIVING_SIDE_LEFT\x10\x01\x12\x16\n\x12\x44RIVING_SIDE_RIGHT\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mathworks.roadrunner.core_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_DRIVINGSIDE']._serialized_start=57
  _globals['_DRIVINGSIDE']._serialized_end=147
# @@protoc_insertion_point(module_scope)
