# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mathworks/scenario/simulation/action_status.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mathworks.scenario.simulation import action_pb2 as mathworks_dot_scenario_dot_simulation_dot_action__pb2
from mathworks.scenario.simulation import condition_status_pb2 as mathworks_dot_scenario_dot_simulation_dot_condition__status__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1mathworks/scenario/simulation/action_status.proto\x12\x1dmathworks.scenario.simulation\x1a*mathworks/scenario/simulation/action.proto\x1a\x34mathworks/scenario/simulation/condition_status.proto\"\xb3\x01\n\x0c\x41\x63tionStatus\x12\n\n\x02id\x18\x01 \x01(\t\x12M\n\x13\x61\x63tion_event_status\x18\x02 \x01(\x0e\x32\x30.mathworks.scenario.simulation.ActionEventStatus\x12H\n\x10\x63ondition_status\x18\x03 \x01(\x0b\x32..mathworks.scenario.simulation.ConditionStatusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mathworks.scenario.simulation.action_status_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_ACTIONSTATUS']._serialized_start=183
  _globals['_ACTIONSTATUS']._serialized_end=362
# @@protoc_insertion_point(module_scope)
