# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mathworks/scenario/simulation/attributes.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mathworks.scenario.common import array_pb2 as mathworks_dot_scenario_dot_common_dot_array__pb2
from mathworks.scenario.common import core_pb2 as mathworks_dot_scenario_dot_common_dot_core__pb2
from mathworks.scenario.common import geometry_pb2 as mathworks_dot_scenario_dot_common_dot_geometry__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.mathworks/scenario/simulation/attributes.proto\x12\x1dmathworks.scenario.simulation\x1a%mathworks/scenario/common/array.proto\x1a$mathworks/scenario/common/core.proto\x1a(mathworks/scenario/common/geometry.proto\"\xed\x01\n\tAttribute\x12\x33\n\x05\x63olor\x18\x01 \x01(\x0b\x32$.mathworks.scenario.common.ColorRGBA\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x33\n\x05point\x18\x03 \x01(\x0b\x32\".mathworks.scenario.common.Vector3H\x00\x12/\n\x04path\x18\x04 \x01(\x0b\x32\x1f.mathworks.scenario.common.PathH\x00\x12/\n\x04\x64\x61ta\x18\x05 \x01(\x0b\x32\x1f.mathworks.scenario.common.DataH\x00\x42\x06\n\x04typeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mathworks.scenario.simulation.attributes_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_ATTRIBUTE']._serialized_start=201
  _globals['_ATTRIBUTE']._serialized_end=438
# @@protoc_insertion_point(module_scope)
