# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mathworks/scenario/simulation/behavior.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mathworks.scenario.simulation import attributes_pb2 as mathworks_dot_scenario_dot_simulation_dot_attributes__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,mathworks/scenario/simulation/behavior.proto\x12\x1dmathworks.scenario.simulation\x1a.mathworks/scenario/simulation/attributes.proto\"\xae\x03\n\x08\x42\x65havior\x12\n\n\x02id\x18\x01 \x01(\t\x12\x17\n\x0f\x61sset_reference\x18\x02 \x01(\t\x12<\n\nparameters\x18\x03 \x03(\x0b\x32(.mathworks.scenario.simulation.Attribute\x12P\n\x13roadrunner_behavior\x18\x04 \x01(\x0b\x32\x31.mathworks.scenario.simulation.RoadRunnerBehaviorH\x00\x12L\n\x11simulink_behavior\x18\x05 \x01(\x0b\x32/.mathworks.scenario.simulation.SimulinkBehaviorH\x00\x12L\n\x11\x65xternal_behavior\x18\x06 \x01(\x0b\x32/.mathworks.scenario.simulation.ExternalBehaviorH\x00\x12@\n\x0bno_behavior\x18\x07 \x01(\x0b\x32).mathworks.scenario.simulation.NoBehaviorH\x00\x42\x0f\n\rplatform_type\"\x14\n\x12RoadRunnerBehavior\"\xbd\x01\n\x10SimulinkBehavior\x12\x19\n\x11\x61rtifact_location\x18\x01 \x01(\t\x12\x46\n\x0f\x62\x65havior_format\x18\x02 \x01(\x0e\x32-.mathworks.scenario.simulation.BehaviorFormat\x12\x46\n\x0fsimulation_mode\x18\x03 \x01(\x0e\x32-.mathworks.scenario.simulation.SimulationMode\"A\n\x10\x45xternalBehavior\x12\x15\n\rplatform_name\x18\x01 \x01(\t\x12\x16\n\x0emodel_location\x18\x02 \x01(\t\"\x0c\n\nNoBehavior*\x7f\n\x0e\x42\x65haviorFormat\x12\x1f\n\x1b\x42\x45HAVIOR_FORMAT_UNSPECIFIED\x10\x00\x12\"\n\x1e\x42\x45HAVIOR_FORMAT_SIMULINK_MODEL\x10\x01\x12(\n$BEHAVIOR_FORMAT_MATLAB_SYSTEM_OBJECT\x10\x02*s\n\x0eSimulationMode\x12\x1f\n\x1bSIMULATION_MODE_UNSPECIFIED\x10\x00\x12\x1f\n\x1bSIMULATION_MODE_INTERPRETED\x10\x01\x12\x1f\n\x1bSIMULATION_MODE_ACCELERATED\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mathworks.scenario.simulation.behavior_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_BEHAVIORFORMAT']._serialized_start=855
  _globals['_BEHAVIORFORMAT']._serialized_end=982
  _globals['_SIMULATIONMODE']._serialized_start=984
  _globals['_SIMULATIONMODE']._serialized_end=1099
  _globals['_BEHAVIOR']._serialized_start=128
  _globals['_BEHAVIOR']._serialized_end=558
  _globals['_ROADRUNNERBEHAVIOR']._serialized_start=560
  _globals['_ROADRUNNERBEHAVIOR']._serialized_end=580
  _globals['_SIMULINKBEHAVIOR']._serialized_start=583
  _globals['_SIMULINKBEHAVIOR']._serialized_end=772
  _globals['_EXTERNALBEHAVIOR']._serialized_start=774
  _globals['_EXTERNALBEHAVIOR']._serialized_end=839
  _globals['_NOBEHAVIOR']._serialized_start=841
  _globals['_NOBEHAVIOR']._serialized_end=853
# @@protoc_insertion_point(module_scope)
