# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mathworks/scenario/simulation/cosim_mgr.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mathworks.scenario.simulation import cosim_pb2 as mathworks_dot_scenario_dot_simulation_dot_cosim__pb2
from mathworks.scenario.simulation import event_pb2 as mathworks_dot_scenario_dot_simulation_dot_event__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-mathworks/scenario/simulation/cosim_mgr.proto\x12\x1dmathworks.scenario.simulation\x1a)mathworks/scenario/simulation/cosim.proto\x1a)mathworks/scenario/simulation/event.proto2\xa4\x08\n\x0f\x43oSimulationMgr\x12\x7f\n\x0eRegisterClient\x12\x34.mathworks.scenario.simulation.RegisterClientRequest\x1a\x35.mathworks.scenario.simulation.RegisterClientResponse\"\x00\x12m\n\x08SetReady\x12..mathworks.scenario.simulation.SetReadyRequest\x1a/.mathworks.scenario.simulation.SetReadyResponse\"\x00\x12j\n\x07SetBusy\x12-.mathworks.scenario.simulation.SetBusyRequest\x1a..mathworks.scenario.simulation.SetBusyResponse\"\x00\x12r\n\x0fSubscribeEvents\x12\x35.mathworks.scenario.simulation.SubscribeEventsRequest\x1a$.mathworks.scenario.simulation.Event\"\x00\x30\x01\x12\x7f\n\x0e\x41\x64\x64Simulations\x12\x34.mathworks.scenario.simulation.AddSimulationsRequest\x1a\x35.mathworks.scenario.simulation.AddSimulationsResponse\"\x00\x12\x88\x01\n\x11RemoveSimulations\x12\x37.mathworks.scenario.simulation.RemoveSimulationsRequest\x1a\x38.mathworks.scenario.simulation.RemoveSimulationsResponse\"\x00\x12\xa9\x01\n\x1cGetSimulationServiceProfiles\x12\x42.mathworks.scenario.simulation.GetSimulationServiceProfilesRequest\x1a\x43.mathworks.scenario.simulation.GetSimulationServiceProfilesResponse\"\x00\x12\x88\x01\n\x11LaunchSimulations\x12\x37.mathworks.scenario.simulation.LaunchSimulationsRequest\x1a\x38.mathworks.scenario.simulation.LaunchSimulationsResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mathworks.scenario.simulation.cosim_mgr_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_COSIMULATIONMGR']._serialized_start=167
  _globals['_COSIMULATIONMGR']._serialized_end=1227
# @@protoc_insertion_point(module_scope)
