# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from mathworks.scenario.simulation import cosim_pb2 as mathworks_dot_scenario_dot_simulation_dot_cosim__pb2
from mathworks.scenario.simulation import event_pb2 as mathworks_dot_scenario_dot_simulation_dot_event__pb2


class CoSimulationApiStub(object):
    """Service for the RoadRunner CoSimulation API
    - Type definitions in cosim.proto
    ////////////////////////////////////
    Client connection and subscriptions
    ////////////////////////////////////
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterClient = channel.unary_unary(
                '/mathworks.scenario.simulation.CoSimulationApi/RegisterClient',
                request_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.RegisterClientRequest.SerializeToString,
                response_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.RegisterClientResponse.FromString,
                )
        self.SetReady = channel.unary_unary(
                '/mathworks.scenario.simulation.CoSimulationApi/SetReady',
                request_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.SetReadyRequest.SerializeToString,
                response_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.SetReadyResponse.FromString,
                )
        self.SetBusy = channel.unary_unary(
                '/mathworks.scenario.simulation.CoSimulationApi/SetBusy',
                request_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.SetBusyRequest.SerializeToString,
                response_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.SetBusyResponse.FromString,
                )
        self.SubscribeEvents = channel.unary_stream(
                '/mathworks.scenario.simulation.CoSimulationApi/SubscribeEvents',
                request_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.SubscribeEventsRequest.SerializeToString,
                response_deserializer=mathworks_dot_scenario_dot_simulation_dot_event__pb2.Event.FromString,
                )
        self.UploadMap = channel.unary_unary(
                '/mathworks.scenario.simulation.CoSimulationApi/UploadMap',
                request_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.UploadMapRequest.SerializeToString,
                response_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.UploadMapResponse.FromString,
                )
        self.DownloadMap = channel.unary_unary(
                '/mathworks.scenario.simulation.CoSimulationApi/DownloadMap',
                request_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.DownloadMapRequest.SerializeToString,
                response_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.DownloadMapResponse.FromString,
                )
        self.UploadScenario = channel.unary_unary(
                '/mathworks.scenario.simulation.CoSimulationApi/UploadScenario',
                request_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.UploadScenarioRequest.SerializeToString,
                response_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.UploadScenarioResponse.FromString,
                )
        self.DownloadScenario = channel.unary_unary(
                '/mathworks.scenario.simulation.CoSimulationApi/DownloadScenario',
                request_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.DownloadScenarioRequest.SerializeToString,
                response_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.DownloadScenarioResponse.FromString,
                )
        self.SetSimulationSettings = channel.unary_unary(
                '/mathworks.scenario.simulation.CoSimulationApi/SetSimulationSettings',
                request_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.SetSimulationSettingsRequest.SerializeToString,
                response_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.SetSimulationSettingsResponse.FromString,
                )
        self.SetSimulationPace = channel.unary_unary(
                '/mathworks.scenario.simulation.CoSimulationApi/SetSimulationPace',
                request_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.SetSimulationPaceRequest.SerializeToString,
                response_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.SetSimulationPaceResponse.FromString,
                )
        self.GetSimulationSettings = channel.unary_unary(
                '/mathworks.scenario.simulation.CoSimulationApi/GetSimulationSettings',
                request_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.GetSimulationSettingsRequest.SerializeToString,
                response_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.GetSimulationSettingsResponse.FromString,
                )
        self.StartSimulation = channel.unary_unary(
                '/mathworks.scenario.simulation.CoSimulationApi/StartSimulation',
                request_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.StartSimulationRequest.SerializeToString,
                response_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.StartSimulationResponse.FromString,
                )
        self.RestartSimulation = channel.unary_unary(
                '/mathworks.scenario.simulation.CoSimulationApi/RestartSimulation',
                request_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.RestartSimulationRequest.SerializeToString,
                response_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.RestartSimulationResponse.FromString,
                )
        self.StopSimulation = channel.unary_unary(
                '/mathworks.scenario.simulation.CoSimulationApi/StopSimulation',
                request_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.StopSimulationRequest.SerializeToString,
                response_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.StopSimulationResponse.FromString,
                )
        self.StopSimulationRequested = channel.unary_unary(
                '/mathworks.scenario.simulation.CoSimulationApi/StopSimulationRequested',
                request_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.StopSimulationRequest.SerializeToString,
                response_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.StopSimulationResponse.FromString,
                )
        self.StepSimulation = channel.unary_unary(
                '/mathworks.scenario.simulation.CoSimulationApi/StepSimulation',
                request_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.StepSimulationRequest.SerializeToString,
                response_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.StepSimulationResponse.FromString,
                )
        self.ToggleSimulationPaused = channel.unary_unary(
                '/mathworks.scenario.simulation.CoSimulationApi/ToggleSimulationPaused',
                request_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.ToggleSimulationPausedRequest.SerializeToString,
                response_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.ToggleSimulationPausedResponse.FromString,
                )
        self.GetSimulationStatus = channel.unary_unary(
                '/mathworks.scenario.simulation.CoSimulationApi/GetSimulationStatus',
                request_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.GetSimulationStatusRequest.SerializeToString,
                response_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.GetSimulationStatusResponse.FromString,
                )
        self.GetSimulationTime = channel.unary_unary(
                '/mathworks.scenario.simulation.CoSimulationApi/GetSimulationTime',
                request_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.GetSimulationTimeRequest.SerializeToString,
                response_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.GetSimulationTimeResponse.FromString,
                )
        self.SetRuntimeActors = channel.unary_unary(
                '/mathworks.scenario.simulation.CoSimulationApi/SetRuntimeActors',
                request_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.SetRuntimeActorsRequest.SerializeToString,
                response_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.SetRuntimeActorsResponse.FromString,
                )
        self.SetActorPoses = channel.unary_unary(
                '/mathworks.scenario.simulation.CoSimulationApi/SetActorPoses',
                request_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.SetActorPosesRequest.SerializeToString,
                response_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.SetActorPosesResponse.FromString,
                )
        self.SetVehiclePoses = channel.unary_unary(
                '/mathworks.scenario.simulation.CoSimulationApi/SetVehiclePoses',
                request_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.SetVehiclePosesRequest.SerializeToString,
                response_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.SetVehiclePosesResponse.FromString,
                )
        self.GetRuntimeActors = channel.unary_unary(
                '/mathworks.scenario.simulation.CoSimulationApi/GetRuntimeActors',
                request_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.GetRuntimeActorsRequest.SerializeToString,
                response_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.GetRuntimeActorsResponse.FromString,
                )
        self.GetActors = channel.unary_unary(
                '/mathworks.scenario.simulation.CoSimulationApi/GetActors',
                request_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.GetActorsRequest.SerializeToString,
                response_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.GetActorsResponse.FromString,
                )
        self.GetActorPoses = channel.unary_unary(
                '/mathworks.scenario.simulation.CoSimulationApi/GetActorPoses',
                request_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.GetActorPosesRequest.SerializeToString,
                response_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.GetActorPosesResponse.FromString,
                )
        self.GetGeodeticCoordinate = channel.unary_unary(
                '/mathworks.scenario.simulation.CoSimulationApi/GetGeodeticCoordinate',
                request_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.GetGeodeticCoordinateRequest.SerializeToString,
                response_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.GetGeodeticCoordinateResponse.FromString,
                )
        self.NotifyActionComplete = channel.unary_unary(
                '/mathworks.scenario.simulation.CoSimulationApi/NotifyActionComplete',
                request_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.NotifyActionCompleteRequest.SerializeToString,
                response_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.NotifyActionCompleteResponse.FromString,
                )
        self.SendEvents = channel.unary_unary(
                '/mathworks.scenario.simulation.CoSimulationApi/SendEvents',
                request_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.SendEventsRequest.SerializeToString,
                response_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.SendEventsResponse.FromString,
                )
        self.ReceiveEvents = channel.unary_unary(
                '/mathworks.scenario.simulation.CoSimulationApi/ReceiveEvents',
                request_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.ReceiveEventsRequest.SerializeToString,
                response_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.ReceiveEventsResponse.FromString,
                )
        self.GetPhaseStatus = channel.unary_unary(
                '/mathworks.scenario.simulation.CoSimulationApi/GetPhaseStatus',
                request_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.GetPhaseStatusRequest.SerializeToString,
                response_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.GetPhaseStatusResponse.FromString,
                )
        self.QueryCommunicationLog = channel.unary_unary(
                '/mathworks.scenario.simulation.CoSimulationApi/QueryCommunicationLog',
                request_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.QueryCommunicationLogRequest.SerializeToString,
                response_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.QueryCommunicationLogResponse.FromString,
                )
        self.EnableCommunicationLogging = channel.unary_unary(
                '/mathworks.scenario.simulation.CoSimulationApi/EnableCommunicationLogging',
                request_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.EnableCommunicationLoggingRequest.SerializeToString,
                response_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.EnableCommunicationLoggingResponse.FromString,
                )
        self.QueryWorldRuntimeLog = channel.unary_unary(
                '/mathworks.scenario.simulation.CoSimulationApi/QueryWorldRuntimeLog',
                request_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.QueryWorldRuntimeLogRequest.SerializeToString,
                response_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.QueryWorldRuntimeLogResponse.FromString,
                )
        self.EnableWorldRuntimeLogging = channel.unary_unary(
                '/mathworks.scenario.simulation.CoSimulationApi/EnableWorldRuntimeLogging',
                request_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.EnableWorldRuntimeLoggingRequest.SerializeToString,
                response_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.EnableWorldRuntimeLoggingResponse.FromString,
                )
        self.AddDiagnosticMessage = channel.unary_unary(
                '/mathworks.scenario.simulation.CoSimulationApi/AddDiagnosticMessage',
                request_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.AddDiagnosticMessageRequest.SerializeToString,
                response_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.AddDiagnosticMessageResponse.FromString,
                )
        self.QueryDiagnosticMessageLog = channel.unary_unary(
                '/mathworks.scenario.simulation.CoSimulationApi/QueryDiagnosticMessageLog',
                request_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.QueryDiagnosticMessageLogRequest.SerializeToString,
                response_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.QueryDiagnosticMessageLogResponse.FromString,
                )


class CoSimulationApiServicer(object):
    """Service for the RoadRunner CoSimulation API
    - Type definitions in cosim.proto
    ////////////////////////////////////
    Client connection and subscriptions
    ////////////////////////////////////
    """

    def RegisterClient(self, request, context):
        """Initialization function where calling clients are assigned an id.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetReady(self, request, context):
        """Registers the calling client as ready to proceed with the next update.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetBusy(self, request, context):
        """Notify that the client is alive and busy
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeEvents(self, request, context):
        """Registers the calling client to receive events.
        Note that this is a long-lived stream, and persists until the client or the server shuts down.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadMap(self, request, context):
        """////////////////////////////////////
        Scene and map access interface
        ////////////////////////////////////  

        Upload the HD map
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadMap(self, request, context):
        """Download the HD map
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadScenario(self, request, context):
        """////////////////////////////////////
        Scenario access interface
        ////////////////////////////////////

        Uploads the provided scenario making it available for simulation.
        - Overwrites any previously uploaded scenario
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadScenario(self, request, context):
        """Download the most recently uploaded scenario
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSimulationSettings(self, request, context):
        """////////////////////////////////////
        Simulation settings access interface
        ////////////////////////////////////

        Set simulation settings
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSimulationPace(self, request, context):
        """Request the server the change the pace of simulation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSimulationSettings(self, request, context):
        """Get simulation settings
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartSimulation(self, request, context):
        """////////////////////////////////////
        Simulation control interface
        ////////////////////////////////////

        Requests that the simulation start.
        - Does nothing if the simulation is already running.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RestartSimulation(self, request, context):
        """Request to immediately stop current run and start off a new run.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopSimulation(self, request, context):
        """A blocking call that requests for the simulation to stop. The RPC call returns with
        a response after simulation has stopped.
        - Does nothing if the simulation is not already running.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopSimulationRequested(self, request, context):
        """A non-blocking call to request for the simulation to stop. The RPC call returns
        immediately with a response and does not wait until simulation has actually stopped.
        - Does nothing if the simulation is not already running.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StepSimulation(self, request, context):
        """If the simulation is paused, requests to advance the simulation by a single
        time step and remain paused. 
        - This service record the single stepping request and return without waiting
        for simulation to complete.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ToggleSimulationPaused(self, request, context):
        """Request that the simulation be paused or unpaused.

        Upon pause requested, simulation engine will:
        - Complete operations of the current time step, including the simulation step
        event and the simulation post-step event
        - Advance time
        - Notify clients that simulation is paused (via a SimulationStatusChangedEvent)
        - Pause without proceeding

        Upon unpause requested, simulation engine will:
        - Notify clients that simulation is running (via a SimulationStatusChangedEvent)
        - Resume simulation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSimulationStatus(self, request, context):
        """Get current simulation status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSimulationTime(self, request, context):
        """Get current simulation time
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRuntimeActors(self, request, context):
        """////////////////////////////////////
        World states access interface
        ////////////////////////////////////  

        Submits actor runtime states to the server.
        Note that:
        - This call shall be placed as a part of event listener callback of
        a simulation step event.
        - The set values will not be committed by the server until all the clients
        has acknowledged the step event.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetActorPoses(self, request, context):
        """Set runtime pose related attributes on one or multiple actors
        - This service is applicable to all types of actors
        - Pose related attributes include e.g., location, heading, velocity etc.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetVehiclePoses(self, request, context):
        """Set runtime pose related attributes on vehicle actors
        - This service is applicable to vehicle actors
        - In addition to pose related attributes that all actor types have, this service
        additionally set vehicle specific attributes such as wheel poses
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRuntimeActors(self, request, context):
        """Returns the requested actors' runtime attributes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActors(self, request, context):
        """Returns the requested actors.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActorPoses(self, request, context):
        """Return actor poses in requested reference frame
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGeodeticCoordinate(self, request, context):
        """Return geodetic coordinates from cartesian coordinates in requested frame
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NotifyActionComplete(self, request, context):
        """Notify the scenario simulation engine that an actor action has completed
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendEvents(self, request, context):
        """Send logic events.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceiveEvents(self, request, context):
        """Receive logic events.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPhaseStatus(self, request, context):
        """Returns the requested phase's runtime status.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryCommunicationLog(self, request, context):
        """////////////////////////////////////
        Simulation logging interface
        ////////////////////////////////////

        Query the server for communication log. The query can be to return all the messages, info, warning or errors,
        messages pertaining to a particular client etc.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnableCommunicationLogging(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryWorldRuntimeLog(self, request, context):
        """Query the server for communication log. The query can be to return all the messages, info, warning or errors,
        messages pertaining to a particular client etc.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnableWorldRuntimeLogging(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddDiagnosticMessage(self, request, context):
        """Add a diagnostic message to the server. The diagnostic message can be information, warning or error.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryDiagnosticMessageLog(self, request, context):
        """Query the server for diagnostic messages. The query can be to return all the messages, info, warning or errors,
        messages pertaining to a particular client etc.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoSimulationApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterClient': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterClient,
                    request_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.RegisterClientRequest.FromString,
                    response_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.RegisterClientResponse.SerializeToString,
            ),
            'SetReady': grpc.unary_unary_rpc_method_handler(
                    servicer.SetReady,
                    request_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.SetReadyRequest.FromString,
                    response_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.SetReadyResponse.SerializeToString,
            ),
            'SetBusy': grpc.unary_unary_rpc_method_handler(
                    servicer.SetBusy,
                    request_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.SetBusyRequest.FromString,
                    response_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.SetBusyResponse.SerializeToString,
            ),
            'SubscribeEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeEvents,
                    request_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.SubscribeEventsRequest.FromString,
                    response_serializer=mathworks_dot_scenario_dot_simulation_dot_event__pb2.Event.SerializeToString,
            ),
            'UploadMap': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadMap,
                    request_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.UploadMapRequest.FromString,
                    response_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.UploadMapResponse.SerializeToString,
            ),
            'DownloadMap': grpc.unary_unary_rpc_method_handler(
                    servicer.DownloadMap,
                    request_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.DownloadMapRequest.FromString,
                    response_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.DownloadMapResponse.SerializeToString,
            ),
            'UploadScenario': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadScenario,
                    request_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.UploadScenarioRequest.FromString,
                    response_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.UploadScenarioResponse.SerializeToString,
            ),
            'DownloadScenario': grpc.unary_unary_rpc_method_handler(
                    servicer.DownloadScenario,
                    request_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.DownloadScenarioRequest.FromString,
                    response_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.DownloadScenarioResponse.SerializeToString,
            ),
            'SetSimulationSettings': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSimulationSettings,
                    request_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.SetSimulationSettingsRequest.FromString,
                    response_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.SetSimulationSettingsResponse.SerializeToString,
            ),
            'SetSimulationPace': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSimulationPace,
                    request_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.SetSimulationPaceRequest.FromString,
                    response_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.SetSimulationPaceResponse.SerializeToString,
            ),
            'GetSimulationSettings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSimulationSettings,
                    request_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.GetSimulationSettingsRequest.FromString,
                    response_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.GetSimulationSettingsResponse.SerializeToString,
            ),
            'StartSimulation': grpc.unary_unary_rpc_method_handler(
                    servicer.StartSimulation,
                    request_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.StartSimulationRequest.FromString,
                    response_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.StartSimulationResponse.SerializeToString,
            ),
            'RestartSimulation': grpc.unary_unary_rpc_method_handler(
                    servicer.RestartSimulation,
                    request_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.RestartSimulationRequest.FromString,
                    response_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.RestartSimulationResponse.SerializeToString,
            ),
            'StopSimulation': grpc.unary_unary_rpc_method_handler(
                    servicer.StopSimulation,
                    request_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.StopSimulationRequest.FromString,
                    response_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.StopSimulationResponse.SerializeToString,
            ),
            'StopSimulationRequested': grpc.unary_unary_rpc_method_handler(
                    servicer.StopSimulationRequested,
                    request_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.StopSimulationRequest.FromString,
                    response_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.StopSimulationResponse.SerializeToString,
            ),
            'StepSimulation': grpc.unary_unary_rpc_method_handler(
                    servicer.StepSimulation,
                    request_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.StepSimulationRequest.FromString,
                    response_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.StepSimulationResponse.SerializeToString,
            ),
            'ToggleSimulationPaused': grpc.unary_unary_rpc_method_handler(
                    servicer.ToggleSimulationPaused,
                    request_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.ToggleSimulationPausedRequest.FromString,
                    response_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.ToggleSimulationPausedResponse.SerializeToString,
            ),
            'GetSimulationStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSimulationStatus,
                    request_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.GetSimulationStatusRequest.FromString,
                    response_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.GetSimulationStatusResponse.SerializeToString,
            ),
            'GetSimulationTime': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSimulationTime,
                    request_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.GetSimulationTimeRequest.FromString,
                    response_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.GetSimulationTimeResponse.SerializeToString,
            ),
            'SetRuntimeActors': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRuntimeActors,
                    request_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.SetRuntimeActorsRequest.FromString,
                    response_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.SetRuntimeActorsResponse.SerializeToString,
            ),
            'SetActorPoses': grpc.unary_unary_rpc_method_handler(
                    servicer.SetActorPoses,
                    request_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.SetActorPosesRequest.FromString,
                    response_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.SetActorPosesResponse.SerializeToString,
            ),
            'SetVehiclePoses': grpc.unary_unary_rpc_method_handler(
                    servicer.SetVehiclePoses,
                    request_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.SetVehiclePosesRequest.FromString,
                    response_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.SetVehiclePosesResponse.SerializeToString,
            ),
            'GetRuntimeActors': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRuntimeActors,
                    request_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.GetRuntimeActorsRequest.FromString,
                    response_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.GetRuntimeActorsResponse.SerializeToString,
            ),
            'GetActors': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActors,
                    request_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.GetActorsRequest.FromString,
                    response_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.GetActorsResponse.SerializeToString,
            ),
            'GetActorPoses': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActorPoses,
                    request_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.GetActorPosesRequest.FromString,
                    response_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.GetActorPosesResponse.SerializeToString,
            ),
            'GetGeodeticCoordinate': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGeodeticCoordinate,
                    request_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.GetGeodeticCoordinateRequest.FromString,
                    response_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.GetGeodeticCoordinateResponse.SerializeToString,
            ),
            'NotifyActionComplete': grpc.unary_unary_rpc_method_handler(
                    servicer.NotifyActionComplete,
                    request_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.NotifyActionCompleteRequest.FromString,
                    response_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.NotifyActionCompleteResponse.SerializeToString,
            ),
            'SendEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.SendEvents,
                    request_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.SendEventsRequest.FromString,
                    response_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.SendEventsResponse.SerializeToString,
            ),
            'ReceiveEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveEvents,
                    request_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.ReceiveEventsRequest.FromString,
                    response_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.ReceiveEventsResponse.SerializeToString,
            ),
            'GetPhaseStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPhaseStatus,
                    request_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.GetPhaseStatusRequest.FromString,
                    response_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.GetPhaseStatusResponse.SerializeToString,
            ),
            'QueryCommunicationLog': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryCommunicationLog,
                    request_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.QueryCommunicationLogRequest.FromString,
                    response_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.QueryCommunicationLogResponse.SerializeToString,
            ),
            'EnableCommunicationLogging': grpc.unary_unary_rpc_method_handler(
                    servicer.EnableCommunicationLogging,
                    request_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.EnableCommunicationLoggingRequest.FromString,
                    response_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.EnableCommunicationLoggingResponse.SerializeToString,
            ),
            'QueryWorldRuntimeLog': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryWorldRuntimeLog,
                    request_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.QueryWorldRuntimeLogRequest.FromString,
                    response_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.QueryWorldRuntimeLogResponse.SerializeToString,
            ),
            'EnableWorldRuntimeLogging': grpc.unary_unary_rpc_method_handler(
                    servicer.EnableWorldRuntimeLogging,
                    request_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.EnableWorldRuntimeLoggingRequest.FromString,
                    response_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.EnableWorldRuntimeLoggingResponse.SerializeToString,
            ),
            'AddDiagnosticMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.AddDiagnosticMessage,
                    request_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.AddDiagnosticMessageRequest.FromString,
                    response_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.AddDiagnosticMessageResponse.SerializeToString,
            ),
            'QueryDiagnosticMessageLog': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryDiagnosticMessageLog,
                    request_deserializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.QueryDiagnosticMessageLogRequest.FromString,
                    response_serializer=mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.QueryDiagnosticMessageLogResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mathworks.scenario.simulation.CoSimulationApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CoSimulationApi(object):
    """Service for the RoadRunner CoSimulation API
    - Type definitions in cosim.proto
    ////////////////////////////////////
    Client connection and subscriptions
    ////////////////////////////////////
    """

    @staticmethod
    def RegisterClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mathworks.scenario.simulation.CoSimulationApi/RegisterClient',
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.RegisterClientRequest.SerializeToString,
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.RegisterClientResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetReady(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mathworks.scenario.simulation.CoSimulationApi/SetReady',
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.SetReadyRequest.SerializeToString,
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.SetReadyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetBusy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mathworks.scenario.simulation.CoSimulationApi/SetBusy',
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.SetBusyRequest.SerializeToString,
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.SetBusyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SubscribeEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/mathworks.scenario.simulation.CoSimulationApi/SubscribeEvents',
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.SubscribeEventsRequest.SerializeToString,
            mathworks_dot_scenario_dot_simulation_dot_event__pb2.Event.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UploadMap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mathworks.scenario.simulation.CoSimulationApi/UploadMap',
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.UploadMapRequest.SerializeToString,
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.UploadMapResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DownloadMap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mathworks.scenario.simulation.CoSimulationApi/DownloadMap',
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.DownloadMapRequest.SerializeToString,
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.DownloadMapResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UploadScenario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mathworks.scenario.simulation.CoSimulationApi/UploadScenario',
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.UploadScenarioRequest.SerializeToString,
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.UploadScenarioResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DownloadScenario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mathworks.scenario.simulation.CoSimulationApi/DownloadScenario',
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.DownloadScenarioRequest.SerializeToString,
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.DownloadScenarioResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetSimulationSettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mathworks.scenario.simulation.CoSimulationApi/SetSimulationSettings',
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.SetSimulationSettingsRequest.SerializeToString,
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.SetSimulationSettingsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetSimulationPace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mathworks.scenario.simulation.CoSimulationApi/SetSimulationPace',
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.SetSimulationPaceRequest.SerializeToString,
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.SetSimulationPaceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSimulationSettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mathworks.scenario.simulation.CoSimulationApi/GetSimulationSettings',
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.GetSimulationSettingsRequest.SerializeToString,
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.GetSimulationSettingsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StartSimulation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mathworks.scenario.simulation.CoSimulationApi/StartSimulation',
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.StartSimulationRequest.SerializeToString,
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.StartSimulationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RestartSimulation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mathworks.scenario.simulation.CoSimulationApi/RestartSimulation',
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.RestartSimulationRequest.SerializeToString,
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.RestartSimulationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StopSimulation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mathworks.scenario.simulation.CoSimulationApi/StopSimulation',
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.StopSimulationRequest.SerializeToString,
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.StopSimulationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StopSimulationRequested(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mathworks.scenario.simulation.CoSimulationApi/StopSimulationRequested',
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.StopSimulationRequest.SerializeToString,
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.StopSimulationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StepSimulation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mathworks.scenario.simulation.CoSimulationApi/StepSimulation',
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.StepSimulationRequest.SerializeToString,
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.StepSimulationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ToggleSimulationPaused(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mathworks.scenario.simulation.CoSimulationApi/ToggleSimulationPaused',
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.ToggleSimulationPausedRequest.SerializeToString,
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.ToggleSimulationPausedResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSimulationStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mathworks.scenario.simulation.CoSimulationApi/GetSimulationStatus',
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.GetSimulationStatusRequest.SerializeToString,
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.GetSimulationStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSimulationTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mathworks.scenario.simulation.CoSimulationApi/GetSimulationTime',
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.GetSimulationTimeRequest.SerializeToString,
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.GetSimulationTimeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetRuntimeActors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mathworks.scenario.simulation.CoSimulationApi/SetRuntimeActors',
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.SetRuntimeActorsRequest.SerializeToString,
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.SetRuntimeActorsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetActorPoses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mathworks.scenario.simulation.CoSimulationApi/SetActorPoses',
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.SetActorPosesRequest.SerializeToString,
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.SetActorPosesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetVehiclePoses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mathworks.scenario.simulation.CoSimulationApi/SetVehiclePoses',
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.SetVehiclePosesRequest.SerializeToString,
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.SetVehiclePosesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRuntimeActors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mathworks.scenario.simulation.CoSimulationApi/GetRuntimeActors',
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.GetRuntimeActorsRequest.SerializeToString,
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.GetRuntimeActorsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetActors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mathworks.scenario.simulation.CoSimulationApi/GetActors',
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.GetActorsRequest.SerializeToString,
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.GetActorsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetActorPoses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mathworks.scenario.simulation.CoSimulationApi/GetActorPoses',
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.GetActorPosesRequest.SerializeToString,
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.GetActorPosesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetGeodeticCoordinate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mathworks.scenario.simulation.CoSimulationApi/GetGeodeticCoordinate',
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.GetGeodeticCoordinateRequest.SerializeToString,
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.GetGeodeticCoordinateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def NotifyActionComplete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mathworks.scenario.simulation.CoSimulationApi/NotifyActionComplete',
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.NotifyActionCompleteRequest.SerializeToString,
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.NotifyActionCompleteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mathworks.scenario.simulation.CoSimulationApi/SendEvents',
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.SendEventsRequest.SerializeToString,
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.SendEventsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReceiveEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mathworks.scenario.simulation.CoSimulationApi/ReceiveEvents',
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.ReceiveEventsRequest.SerializeToString,
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.ReceiveEventsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPhaseStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mathworks.scenario.simulation.CoSimulationApi/GetPhaseStatus',
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.GetPhaseStatusRequest.SerializeToString,
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.GetPhaseStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def QueryCommunicationLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mathworks.scenario.simulation.CoSimulationApi/QueryCommunicationLog',
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.QueryCommunicationLogRequest.SerializeToString,
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.QueryCommunicationLogResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EnableCommunicationLogging(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mathworks.scenario.simulation.CoSimulationApi/EnableCommunicationLogging',
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.EnableCommunicationLoggingRequest.SerializeToString,
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.EnableCommunicationLoggingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def QueryWorldRuntimeLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mathworks.scenario.simulation.CoSimulationApi/QueryWorldRuntimeLog',
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.QueryWorldRuntimeLogRequest.SerializeToString,
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.QueryWorldRuntimeLogResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EnableWorldRuntimeLogging(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mathworks.scenario.simulation.CoSimulationApi/EnableWorldRuntimeLogging',
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.EnableWorldRuntimeLoggingRequest.SerializeToString,
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.EnableWorldRuntimeLoggingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddDiagnosticMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mathworks.scenario.simulation.CoSimulationApi/AddDiagnosticMessage',
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.AddDiagnosticMessageRequest.SerializeToString,
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.AddDiagnosticMessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def QueryDiagnosticMessageLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mathworks.scenario.simulation.CoSimulationApi/QueryDiagnosticMessageLog',
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.QueryDiagnosticMessageLogRequest.SerializeToString,
            mathworks_dot_scenario_dot_simulation_dot_cosim__pb2.QueryDiagnosticMessageLogResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
