# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mathworks/scenario/simulation/custom_command.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mathworks.scenario.simulation import attributes_pb2 as mathworks_dot_scenario_dot_simulation_dot_attributes__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2mathworks/scenario/simulation/custom_command.proto\x12\x1dmathworks.scenario.simulation\x1a.mathworks/scenario/simulation/attributes.proto\"[\n\rCustomCommand\x12\x0c\n\x04name\x18\x01 \x01(\t\x12<\n\nattributes\x18\x02 \x03(\x0b\x32(.mathworks.scenario.simulation.Attributeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mathworks.scenario.simulation.custom_command_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_CUSTOMCOMMAND']._serialized_start=133
  _globals['_CUSTOMCOMMAND']._serialized_end=224
# @@protoc_insertion_point(module_scope)
