# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mathworks/scenario/simulation/sensor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mathworks.scenario.common import geometry_pb2 as mathworks_dot_scenario_dot_common_dot_geometry__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*mathworks/scenario/simulation/sensor.proto\x12\x1dmathworks.scenario.simulation\x1a(mathworks/scenario/common/geometry.proto\"1\n\x0b\x46ieldOfView\x12\x0f\n\x07\x61zimuth\x18\x01 \x01(\x01\x12\x11\n\televation\x18\x02 \x01(\x01\"\'\n\x0bRangeLimits\x12\x0b\n\x03min\x18\x01 \x01(\x01\x12\x0b\n\x03max\x18\x02 \x01(\x01\"\xf4\x01\n\x0fRayIntersection\x12\x34\n\x08position\x18\x01 \x01(\x0b\x32\".mathworks.scenario.common.Vector3\x12\x10\n\x08\x64istance\x18\x02 \x01(\x01\x12\x32\n\x06normal\x18\x03 \x01(\x0b\x32\".mathworks.scenario.common.Vector3\x12\x11\n\ttarget_id\x18\x04 \x01(\t\x12\x17\n\x0ftarget_material\x18\x05 \x01(\t\x12\x39\n\rray_direction\x18\x06 \x01(\x0b\x32\".mathworks.scenario.common.Vector3\"\x8a\x01\n\x07RayPath\x12:\n\x0estart_position\x18\x01 \x01(\x0b\x32\".mathworks.scenario.common.Vector3\x12\x43\n\x0cinteractions\x18\x02 \x03(\x0b\x32-.mathworks.scenario.simulation.RayInteraction\"\xa3\x01\n\x0eRayInteraction\x12K\n\x10interaction_type\x18\x01 \x01(\x0e\x32\x31.mathworks.scenario.simulation.RayInteractionType\x12\x44\n\x0cintersection\x18\x02 \x01(\x0b\x32..mathworks.scenario.simulation.RayIntersection*\x93\x02\n\x1aSensorDetectionCoordinates\x12,\n(SENSOR_DETECTION_COORDINATES_UNSPECIFIED\x10\x00\x12\x30\n,SENSOR_DETECTION_COORDINATES_WORLD_CARTESIAN\x10\x01\x12/\n+SENSOR_DETECTION_COORDINATES_HOST_CARTESIAN\x10\x02\x12\x31\n-SENSOR_DETECTION_COORDINATES_SENSOR_CARTESIAN\x10\x03\x12\x31\n-SENSOR_DETECTION_COORDINATES_SENSOR_SPHERICAL\x10\x04*\xb0\x01\n\x12RayInteractionType\x12$\n RAY_INTERACTION_TYPE_UNSPECIFIED\x10\x00\x12$\n RAY_INTERACTION_TYPE_DESTINATION\x10\x01\x12#\n\x1fRAY_INTERACTION_TYPE_REFLECTION\x10\x02\x12)\n%RAY_INTERACTION_TYPE_EDGE_DIFFRACTION\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mathworks.scenario.simulation.sensor_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_SENSORDETECTIONCOORDINATES']._serialized_start=766
  _globals['_SENSORDETECTIONCOORDINATES']._serialized_end=1041
  _globals['_RAYINTERACTIONTYPE']._serialized_start=1044
  _globals['_RAYINTERACTIONTYPE']._serialized_end=1220
  _globals['_FIELDOFVIEW']._serialized_start=119
  _globals['_FIELDOFVIEW']._serialized_end=168
  _globals['_RANGELIMITS']._serialized_start=170
  _globals['_RANGELIMITS']._serialized_end=209
  _globals['_RAYINTERSECTION']._serialized_start=212
  _globals['_RAYINTERSECTION']._serialized_end=456
  _globals['_RAYPATH']._serialized_start=459
  _globals['_RAYPATH']._serialized_end=597
  _globals['_RAYINTERACTION']._serialized_start=600
  _globals['_RAYINTERACTION']._serialized_end=763
# @@protoc_insertion_point(module_scope)
