# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mathworks/scenario/simulation/simulation_settings.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7mathworks/scenario/simulation/simulation_settings.proto\x12\x1dmathworks.scenario.simulation\"r\n\x12SimulationSettings\x12\x11\n\tstep_size\x18\x01 \x01(\x01\x12\x1b\n\x13max_simulation_time\x18\x02 \x01(\x01\x12\x13\n\x0bis_pacer_on\x18\x03 \x01(\x08\x12\x17\n\x0fsimulation_pace\x18\x04 \x01(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mathworks.scenario.simulation.simulation_settings_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_SIMULATIONSETTINGS']._serialized_start=90
  _globals['_SIMULATIONSETTINGS']._serialized_end=204
# @@protoc_insertion_point(module_scope)
