# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mathworks/scenario/simulation/transition_dynamics.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7mathworks/scenario/simulation/transition_dynamics.proto\x12\x1dmathworks.scenario.simulation\"\xa5\x01\n\x12TransitionDynamics\x12\x43\n\tdimension\x18\x01 \x01(\x0e\x32\x30.mathworks.scenario.simulation.DynamicsDimension\x12;\n\x05shape\x18\x02 \x01(\x0e\x32,.mathworks.scenario.simulation.DynamicsShape\x12\r\n\x05value\x18\x03 \x01(\x01\"i\n\x16TimeTransitionDynamics\x12;\n\x05shape\x18\x01 \x01(\x0e\x32,.mathworks.scenario.simulation.DynamicsShape\x12\x12\n\ntime_value\x18\x02 \x01(\x01\"X\n\x12\x44ynamicConstraints\x12\x42\n\rdynamic_limit\x18\x01 \x01(\x0b\x32+.mathworks.scenario.simulation.DynamicLimit\"U\n\x0c\x44ynamicLimit\x12\x11\n\tmax_speed\x18\x01 \x01(\x01\x12\x18\n\x10max_acceleration\x18\x02 \x01(\x01\x12\x18\n\x10max_deceleration\x18\x03 \x01(\x01*\x92\x01\n\x11\x44ynamicsDimension\x12\"\n\x1e\x44YNAMICS_DIMENSION_UNSPECIFIED\x10\x00\x12\x1b\n\x17\x44YNAMICS_DIMENSION_RATE\x10\x01\x12\x1b\n\x17\x44YNAMICS_DIMENSION_TIME\x10\x02\x12\x1f\n\x1b\x44YNAMICS_DIMENSION_DISTANCE\x10\x03*}\n\rDynamicsShape\x12\x1e\n\x1a\x44YNAMICS_SHAPE_UNSPECIFIED\x10\x00\x12\x19\n\x15\x44YNAMICS_SHAPE_LINEAR\x10\x01\x12\x18\n\x14\x44YNAMICS_SHAPE_CUBIC\x10\x02\x12\x17\n\x13\x44YNAMICS_SHAPE_STEP\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mathworks.scenario.simulation.transition_dynamics_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_DYNAMICSDIMENSION']._serialized_start=543
  _globals['_DYNAMICSDIMENSION']._serialized_end=689
  _globals['_DYNAMICSSHAPE']._serialized_start=691
  _globals['_DYNAMICSSHAPE']._serialized_end=816
  _globals['_TRANSITIONDYNAMICS']._serialized_start=91
  _globals['_TRANSITIONDYNAMICS']._serialized_end=256
  _globals['_TIMETRANSITIONDYNAMICS']._serialized_start=258
  _globals['_TIMETRANSITIONDYNAMICS']._serialized_end=363
  _globals['_DYNAMICCONSTRAINTS']._serialized_start=365
  _globals['_DYNAMICCONSTRAINTS']._serialized_end=453
  _globals['_DYNAMICLIMIT']._serialized_start=455
  _globals['_DYNAMICLIMIT']._serialized_end=540
# @@protoc_insertion_point(module_scope)
